### ISSUE TITLE
Please explain useage in more detail

### ISSUE THREAD

**Issue by nishantbhat** [OpenFieldReader/OpenFieldReader#1]
Hi,
Can you please explain how to use the command line arguments and pass the image and detect text in form ?

**Comment by doxakis** [comment]
Hi,
I just want to tell you that I saw your message. I will answer you with a complete answer in the next few days.
Thanks

**Comment by nishantbhat** [comment]
Hi ,
Thank you for the response .
Can you please help me how to extract single lines from the form and detect
handwritten text in this link :-

https://github.com/doxakis/form-segmentation

Actually am new to this field and am running out of the time to analyse and
implement with the help of reference notes.

Please help me in this to get the result

Thank you
Nishant Bhat
+91-7829709236

**Comment by nishantbhat** [comment]
Thank you so much. I will be waiting for the next solution of the usage

**Comment by doxakis** [comment]
Hi,

you may want to use the python wrapper (https://github.com/OpenFieldReader/OpenFieldReaderWrapper) since it should be easier and preprocessing will be done for you with opencv.

For convenient, I created a pypi project (`pip install openfieldreaderwrapper`)

If you use linux, simply follow the step here: https://github.com/OpenFieldReader/OpenFieldReader to install the package openfieldreader

On Windows, you may want to do the following:
- On Visual Studio 2017, publish with Release configuration, target framework netcoreapp2.0, deployment mode: self-contained, target runtime: win-x64
- Add the folder containing the OpenFieldReader.exe to the PATH variable of Windows.

I added a new repo: https://github.com/OpenFieldReader/OpenFieldReader-datasets

It shows you how to use it: generate-dataset.py
(I'm using opencv. Make sure to install it: `pip install opencv-python`)

In the folder dataset1 and dataset2, you will find the dataset I will use. For obvious reasons, I had to find out a public dataset and I end up using sudoku grids.. feel limited because it's only letter from 1-9. But, it should be fine to demonstrate what you can do. If you think about it, you can see it as 9 fields with 9 characters each.

In the folder dataset1-cells and dataset2-cells. you will find the result of the extraction. One picture per cell. (letter from 1-9, empty cell and random image sometime)

The algorithm only resolve the segmentation issue (find where are the cells)

![cells](https://user-images.githubusercontent.com/5766482/46992291-5d7fc200-d0d7-11e8-8554-a50ce67091c7.PNG)

Then, you may want to prepare a dataset for training.

Here, I'm considering the letter 1-9, empty cell and random image not relevant to improve the quality of predictions.

![prepare-dataset](https://user-images.githubusercontent.com/5766482/46992301-62dd0c80-d0d7-11e8-9451-7f23c882f9f2.PNG)

Then, implements a CNN (convolutional neural network) and predict the letter if the confident is high enough.

I hope it help you understand what is the purpose of this project and what you can do with it right now.

Thanks and good luck!

**Comment by doxakis** [comment]
Hi, I will close the issue for now. Feel free to open it again.
